name = "LocalSearchSolvers"
uuid = "2b10edaa-728d-4283-ac71-07e312d6ccf3"
authors = ["Jean-Francois Baffier"]
version = "0.1.0"

[deps]
Dictionaries = "85a47980-9c8c-11e8-2b9f-f7ca1fa99fb4"
<<<<<<< HEAD
Lazy = "50d2b5c4-7a5e-59d5-8109-a42b560f39c0"
=======
>>>>>>> Test for domain types and methods. Added Dictionaries.jl

[compat]
Dictionaries = "0.3.4"
Lazy = "0.15"
julia = "1.5"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
